# Generated by Django 4.1.1 on 2022-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('autor_id', models.ManyToManyField(to='libro.autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
