# Generated by Django 4.1.3 on 2022-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libro", "0003_autor_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
